import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import { ReactElement } from 'react'
import Layout from '~/components/Layout'

export default function Home() {

  const {data:session} = useSession()
  console.log(session)
  return (
    <>
      <Head>
        <title>Futsal Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-full h-[9em] md:h-[14em] p-2 bg-red-500 rounded-xl '>
        <h1>Banner</h1>
      </div>

      <div className='w-full mt-4'>
        <div className="w-full flex justify-between items-center">
          <h1>Turnamen</h1>
          <Link href='/tournament/all' className='text-[12px]'>Lihat Semua</Link>
        </div>
        <div className='w-full flex gap-3 overflow-x-auto mt-2'>
          {[...Array(5)].map((tournament, i)=>(
            <Link key={i} href={`/tournament/${i}`}>
              <div className='min-w-[200px] h-[100px] rounded-xl bg-red-500'></div>
            </Link>
          ))}
        </div>
      </div>

      <div className='w-full mt-4'>
        <div className='w-full flex justify-between items-center'>
          <h1>Pertandingan Hari Ini</h1>
          <Link href='/match/all' className='text-[12px]'>Lihat Semua</Link>
        </div>
        <div className='w-full flex flex-col gap-3 mt-2'>
          {Array(5).fill('').map((match, i)=>(
            <Link key={i} href={`/match/${i}`}>
              <div className='w-full bg-slate-500 rounded-xl p-3 flex items-center justify-center gap-3'>
                <div className='flex gap-3 items-center'>
                  <span>Chelsea</span>
                  <div className='w-[40px] h-[40px] bg-red-500 rounded-full'></div>
                </div>
                <span>VS</span>
                <div className='flex gap-3 items-center'>
                  <div className='w-[40px] h-[40px] bg-red-500 rounded-full'></div>
                  <span>Chelsea</span>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement){
  return (
    <Layout>
      {page}
    </Layout>
  )
}